management:
  security:
    enabled: false
    #prometheus+grafana+springboot2监控集成配置
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
      jmx:
        enabled: false
  endpoints:
    web:
      exposure:
        include: 'prometheus'
      base-path: /metrics
      #prometheus+grafana+springboot2监控集成配置